"""
Integration test: broken fences detected by validate-md and surfaced in UI breakdown.

The real-world bug (discovered on KIE post 2013-10-31-configuration-and-convention...):
  Old convert_post.py + html2text produces this for DocBook <div class="example"> blocks:

      [**Example 2.34. kmodule.xml** ```xml
      <kmodule/>
      ```](<http://blog.athico.com/>)[](<http://blog.athico.com/>)

  The closing line is ```](<url>)  — backticks followed by a Markdown link.
  This is NOT a valid CommonMark closing fence (closing fences must have ONLY backticks).

  The original chk_balanced_fences used a naive check (run >= in_fence) that
  treated ```](<url>) as a valid closer.  With multiple DocBook examples, the
  ```](<url>) lines alternately open and close fences, ending with in_fence=0 —
  so the validator reported NO unbalanced_fences even though the page rendered
  entirely as one giant code block.

  The fix: require re.fullmatch(r'`+\\s*', line) for a valid closing fence.
  A line with ```](<url>) after the backticks fails fullmatch and is kept as content.

This test proves the full pipeline:
  1. Broken MD on disk  (simulating old-code-generated content with real URL pattern)
  2. POST /api/posts/{slug}/validate-md  →  md.issues populated in state.json
  3. UI MD⚠ filter + breakdown  →  unbalanced_fences appears

NOTE: the Sparge server must be restarted after patching md_validator.py for the
API tests to pick up the new chk_balanced_fences logic (Python imports are cached
at server startup).

Run with server on localhost:9000:
  python3 -m pytest tests/test_fence_validation.py -v

Playwright required: playwright install chromium
"""
import json
import shutil
import textwrap
import uuid
from pathlib import Path

import pytest

SERVER  = 'http://localhost:9000'
APP_URL = SERVER + '/ui/index.html'
API     = SERVER + '/api'

TS   = '2026-01-01T00:00:00'
SLUG = '2020-01-01-docbook-broken-fences'

# Simulates the REAL pattern found in KIE blog posts generated by old convert_post.py.
# html2text wraps DocBook <div class="example"> content in [...] and appends the href
# as a Markdown link, producing: ```](<http://...>)[](<http://...>)
#
# CRITICAL: the pattern uses MULTIPLE examples so that the old validator's naive
# "run >= in_fence" check treats alternating ```](<url>) lines as open/close pairs,
# yielding in_fence=0 and falsely reporting NO unbalanced_fences.
# The new fullmatch check correctly rejects ```](<url>) as a closer and reports the error.
BROKEN_MD = textwrap.dedent("""\
    ---
    layout: post
    title: "DocBook Broken Fences"
    date: 2020-01-01
    author: Test Author
    categories: []
    tags: []
    original_url: http://example.com/broken-fences
    ---

    Some introductory text about the configuration.

    [**Example 2.34. Author \u2013 kmodule.xml** ```xml
    <kmodule xmlns="http://jboss.org/kie/6.0.0/kmodule">
      <kbase name="rules" packages="org.drools">
        <ksession name="ksession1"/>
      </kbase>
    </kmodule>
    ```](<http://example.com/>)[](<http://example.com/>)

    Some text between examples.

    [](<http://example.com/>)[**Example 2.35. Build and Install \u2013 Maven** ```
    mvn install
    ```](<http://example.com/>)[](<http://example.com/>)

    More content after the examples.
""")


# ── Fixtures ───────────────────────────────────────────────────────────────────

@pytest.fixture(scope='module')
def session():
    try:
        import requests
        s = requests.Session()
        s.get(f'{API}/projects', timeout=3).raise_for_status()
        return s
    except Exception:
        pytest.skip('Server not running on localhost:9000')


@pytest.fixture(scope='module')
def test_project(session, tmp_path_factory):
    import requests

    tmp = tmp_path_factory.mktemp('fence_test')
    uid = uuid.uuid4().hex[:8]

    r = session.post(f'{API}/projects', json={
        'name': f'fence-{uid}',
        'serve_root': str(tmp),
        'posts_dir': 'posts',
        'assets_dir': 'assets',
        'md_dir': 'md',
        'author_filter': '',
    })
    assert r.status_code in (200, 201), f'Project creation failed: {r.text}'
    pid = r.json()['id']

    cfg = session.get(f'{API}/config').json()
    projects_dir = Path(cfg.get('projects_dir', Path.home() / 'sparge-projects'))
    proj_dir = projects_dir / pid
    proj_dir.mkdir(parents=True, exist_ok=True)

    # Write state.json: post exists with md.generated_at (so validate-md can run)
    # md.issues is empty — simulating posts generated before the validator was improved
    state = {
        SLUG: {
            'slug': SLUG,
            'title': 'DocBook Broken Fences',
            'date': '2020-01-01',
            'author': 'Test Author',
            'original_url': f'http://example.com/{SLUG}',
            'ingested_at': TS,
            'reviewed': False,
            'html': {'hash': uuid.uuid4().hex[:12], 'issues': [], 'checked_at': TS},
            'md': {
                'generated_at': TS,
                'html_hash': 'aaa000',
                'issues': [],          # empty — hasn't been validated yet
                'staged': False,
                'validated_at': None,  # never validated
            },
        }
    }
    (proj_dir / 'state.json').write_text(json.dumps(state, indent=2))

    # Write the broken MD file (simulating old-code generation)
    md_dir = tmp / 'md'
    md_dir.mkdir(exist_ok=True)
    (md_dir / f'{SLUG}.md').write_text(BROKEN_MD, encoding='utf-8')

    # Also need posts dir for the project structure
    (tmp / 'posts').mkdir(exist_ok=True)

    session.post(f'{API}/projects/{pid}/activate')

    posts = session.get(f'{API}/posts').json()
    assert len(posts) == 1, f'Expected 1 post, got {len(posts)}'
    assert posts[0]['md'].get('issues') == [], 'md.issues should start empty (pre-validation)'

    yield {'id': pid, 'dir': proj_dir, 'tmp': tmp}

    session.delete(f'{API}/projects/{pid}')
    if proj_dir.exists():
        shutil.rmtree(proj_dir)
    session.post(f'{API}/projects/kie-mark-proctor/activate')


@pytest.fixture(scope='module')
def page(test_project, session):
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        pytest.skip('playwright not installed')

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        pg = browser.new_page(viewport={'width': 1280, 'height': 900})
        pg.goto(APP_URL, wait_until='networkidle')
        pg.wait_for_selector('.pi', timeout=10000)
        yield pg
        browser.close()


# ── Unit: validator detects the broken fence pattern ──────────────────────────

class TestOldValidatorMissedRealPattern:
    """Prove that the OLD naive validator logic (run >= in_fence, no fullmatch check)
    would MISS the unbalanced_fences error in the real-world multi-example pattern.

    This class documents why the simple ```] test was insufficient: the old code
    happened to catch the single-example case (nothing to close the fence) but
    silently passed the multi-example case (pairs of ```](<url>) cancelled out).
    """

    def _old_check(self, md: str) -> bool:
        """Simulate the OLD chk_balanced_fences logic (before fullmatch fix)."""
        import re
        body = md.split('\n---\n', 1)[1] if '\n---\n' in md else md
        in_fence = 0
        for line in body.splitlines():
            m = re.match(r'^(`{3,})', line)
            if m:
                run = len(m.group(1))
                if in_fence == 0:
                    in_fence = run
                elif run >= in_fence:
                    in_fence = 0  # OLD: no fullmatch — ```](<url>) treated as valid closer
        return in_fence != 0  # True = unbalanced

    def test_old_logic_misses_multi_example_pattern(self):
        """OLD validator returns False (no error) for the real multi-example pattern.

        This is the bug: ```](<url>) pairs alternate open/close, leaving in_fence=0.
        This test would have FAILED if written before the fullmatch fix was applied.
        The test documents what would have caught the regression.
        """
        detected = self._old_check(BROKEN_MD)
        # Old logic DOES NOT detect it — this assertion proves the old code was broken
        assert not detected, (
            'This test documents the old behaviour: old validator must NOT detect '
            'the multi-example ```](<url>) pattern. If this fails, the test fixture '
            'has changed and no longer reproduces the real-world bug.')

    def test_new_logic_catches_multi_example_pattern(self):
        """NEW validator (with fullmatch) correctly detects the real pattern."""
        import sys
        sys.path.insert(0, str(Path(__file__).parent.parent / 'scripts'))
        from md_validator import chk_balanced_fences
        issues = chk_balanced_fences(BROKEN_MD, SLUG)
        assert any(i.check == 'unbalanced_fences' for i in issues), (
            'New validator must detect unbalanced_fences in the multi-example pattern. '
            f'Issues: {[i.check for i in issues]}')


class TestValidatorDetectsDocbookFence:
    """The state machine in chk_balanced_fences must correctly detect the
    DocBook [Example N. title ```xml\\ncode\\n```] pattern as unbalanced.

    The ```] token starts a fence (it begins with 3+ backticks) but nothing
    closes it, leaving in_fence != 0 at end of document.
    """

    def test_docbook_inline_fence_detected_as_unbalanced(self):
        """```] opens a fence; no valid closer follows → unbalanced_fences."""
        import sys
        sys.path.insert(0, str(Path(__file__).parent.parent / 'scripts'))
        from md_validator import validate

        issues = validate(BROKEN_MD, SLUG)
        checks = [i.check for i in issues]
        assert 'unbalanced_fences' in checks, (
            'The DocBook [Example N. ```xml\\ncode\\n```] pattern must be detected '
            'as unbalanced_fences. The ```] token opens a fence but no valid closer '
            f'follows. Issues found: {checks}')

    def test_valid_fence_not_flagged(self):
        """A properly fenced code block must NOT trigger unbalanced_fences."""
        import sys
        sys.path.insert(0, str(Path(__file__).parent.parent / 'scripts'))
        from md_validator import validate

        clean_md = textwrap.dedent("""\
            ---
            title: Clean Post
            date: 2020-01-01
            author: Test
            ---

            Some text.

            ```xml
            <kmodule/>
            ```

            More text.
        """)
        issues = validate(clean_md, 'clean-slug')
        checks = [i.check for i in issues]
        assert 'unbalanced_fences' not in checks, (
            f'A properly fenced block must not trigger unbalanced_fences. '
            f'Issues: {checks}')

    def test_fence_closed_by_backtick_bracket_still_unbalanced(self):
        """```] is not a valid CommonMark closing fence (has ] after backticks).
        The state machine must NOT treat it as a closer for an opening fence.
        """
        import sys
        sys.path.insert(0, str(Path(__file__).parent.parent / 'scripts'))
        from md_validator import validate

        # Opening ``` on its own line, then ```] which is not a valid closer
        md = textwrap.dedent("""\
            ---
            title: Test
            date: 2020-01-01
            author: Test
            ---

            ```xml
            <config/>
            ```]

            After.
        """)
        issues = validate(md, 'bracket-slug')
        checks = [i.check for i in issues]
        assert 'unbalanced_fences' in checks, (
            'A fence opened by ``` and "closed" by ```] must still be detected as '
            'unbalanced because ```] is not a valid CommonMark closer (has ] after '
            f'the backticks). Issues found: {checks}')


# ── API: validate-md populates md.issues with unbalanced_fences ───────────────

class TestValidateMdPopulatesIssues:
    """POST /api/posts/{slug}/validate-md must detect unbalanced_fences in
    the broken MD file and store the result in state.json."""

    def test_validate_md_returns_unbalanced_fences(self, session, test_project):
        """validate-md response must include unbalanced_fences in issues list."""
        r = session.post(f'{API}/posts/{SLUG}/validate-md')
        assert r.status_code == 200, f'validate-md failed: {r.text}'

        post = r.json()
        checks = [i['check'] for i in post.get('md', {}).get('issues', [])]
        assert 'unbalanced_fences' in checks, (
            'validate-md must detect unbalanced_fences in the broken MD file. '
            f'Issues returned: {checks}')

    def test_validate_md_persists_to_state(self, session, test_project):
        """After validate-md, GET /api/posts/{slug} must show unbalanced_fences."""
        session.post(f'{API}/posts/{SLUG}/validate-md')  # ensure validated

        post = session.get(f'{API}/posts/{SLUG}').json()
        checks = [i['check'] for i in post.get('md', {}).get('issues', [])]
        assert 'unbalanced_fences' in checks, (
            'unbalanced_fences must be persisted in state.json after validate-md. '
            f'Issues in state: {checks}')

    def test_issue_level_is_error(self, session, test_project):
        """unbalanced_fences must be reported at ERROR level (not WARN)."""
        session.post(f'{API}/posts/{SLUG}/validate-md')

        post = session.get(f'{API}/posts/{SLUG}').json()
        fence_issues = [i for i in post.get('md', {}).get('issues', [])
                        if i['check'] == 'unbalanced_fences']
        assert fence_issues, 'unbalanced_fences issue not found'
        assert fence_issues[0]['level'] == 'ERROR', (
            f'unbalanced_fences must be ERROR level. Got: {fence_issues[0]["level"]}')


# ── UI: unbalanced_fences appears in the MD issues breakdown ──────────────────

class TestUiBreakdownShowsFenceIssue:
    """After validate-md, the MD⚠ filter breakdown in the left nav panel
    must surface unbalanced_fences as a clickable row."""

    def _ensure_validated(self, session):
        """Call validate-md to populate md.issues before the UI test."""
        session.post(f'{API}/posts/{SLUG}/validate-md')

    def _open_md_breakdown(self, page):
        # Expand MD breakdown if not already open
        arrow = page.locator('#md-arr')
        if 'open' not in (arrow.get_attribute('class') or ''):
            page.locator('.srow.expandable').filter(has_text='MD issues').click()
            page.wait_for_timeout(250)

    def test_md_warning_filter_shows_post(self, page, session, test_project):
        """After validate-md, the post must appear in the MD⚠ filter scope."""
        self._ensure_validated(session)
        # Reload page so the UI picks up the updated state
        page.reload(wait_until='networkidle')
        page.wait_for_selector('.pi', timeout=10000)

        page.locator('.filter-always button').filter(has_text='MD⚠').click()
        page.wait_for_timeout(300)

        slugs = {el.get_attribute('data-slug')
                 for el in page.locator('.pi[data-slug]').all()}
        assert SLUG in slugs, (
            f'Post with unbalanced_fences must appear in MD⚠ filter. '
            f'Visible slugs: {slugs}')

    def test_unbalanced_fences_appears_in_md_breakdown(self, page, session, test_project):
        """unbalanced_fences must appear as a row in the expanded MD issues breakdown."""
        self._ensure_validated(session)
        page.reload(wait_until='networkidle')
        page.wait_for_selector('.pi', timeout=10000)

        # Filter to MD⚠ to make the breakdown relevant
        page.locator('.filter-always button').filter(has_text='MD⚠').click()
        page.wait_for_timeout(200)

        self._open_md_breakdown(page)

        keys = {el.get_attribute('data-key')
                for el in page.locator('#md-breakdown .itr').all()}
        assert 'unbalanced_fences' in keys, (
            f'unbalanced_fences must appear in the MD issues breakdown after '
            f'validate-md is run. Breakdown keys visible: {keys}')

    def test_unbalanced_fences_breakdown_count_is_correct(self, page, session, test_project):
        """The unbalanced_fences row must show count=1 (one affected post)."""
        self._ensure_validated(session)
        page.reload(wait_until='networkidle')
        page.wait_for_selector('.pi', timeout=10000)

        page.locator('.filter-always button').filter(has_text='MD⚠').click()
        page.wait_for_timeout(200)
        self._open_md_breakdown(page)

        count_el = page.locator('#md-breakdown .itr[data-key="unbalanced_fences"] .itr-count')
        count_el.wait_for(state='visible', timeout=3000)
        count = int(count_el.inner_text())
        assert count == 1, (
            f'unbalanced_fences breakdown count should be 1, got {count}')

    def test_clicking_unbalanced_fences_filters_post_list(self, page, session, test_project):
        """Clicking the unbalanced_fences row must filter the post list to
        only the affected post."""
        self._ensure_validated(session)
        page.reload(wait_until='networkidle')
        page.wait_for_selector('.pi', timeout=10000)

        page.locator('.filter-always button').filter(has_text='MD⚠').click()
        page.wait_for_timeout(200)
        self._open_md_breakdown(page)

        row = page.locator('#md-breakdown .itr[data-key="unbalanced_fences"]')
        row.wait_for(state='visible', timeout=3000)
        row.click()
        page.wait_for_timeout(300)

        slugs = {el.get_attribute('data-slug')
                 for el in page.locator('.pi[data-slug]').all()}
        assert slugs == {SLUG}, (
            f'Clicking unbalanced_fences must filter to only the affected post. '
            f'Got: {slugs}')
