quarkus.http.port=9001
quarkus.package.jar.type=uber-jar
quarkus.package.output-name=sparge-server
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PATCH,DELETE,OPTIONS

%dev.quarkus.log.level=INFO
%dev.quarkus.log.category."io.sparge".level=DEBUG
